channels:
- anaconda
- conda-forge
- pytorch
dependencies:
- python=3.9.19
- pip:
  - mlflow==2.9.2
  - azureml-train-automl-runtime==1.57.0
  - inference-schema
  - xgboost<=1.5.2
  - azureml-interpret==1.57.0
  - azureml-defaults==1.57.0
  - pytorch-transformers==1.0.0
  - spacy==3.7.4
  - https://aka.ms/automl-resources/packages/en_core_web_sm-3.7.1.tar.gz
- numpy==1.23.5
- pandas==1.3.5
- scikit-learn==1.5.1
- prophet==1.1.4
- holidays==0.54
- psutil==5.9.3
- pytorch==1.11.0
- cudatoolkit==9.0
name: project_environment
